parameters:
  - name: listWorkspaces
    type: object
    default:

    - workspace:
      - name: dev
      environments:
        - name: dev01
          ado_pipeline_environment: dev01
          locations:
            - name: canada-center
              workspace_path: dev/dev01/canada-center
              module_path: modules/dev
              terraform_security_file_name: dev01-security-file
            - name: canada-east
              workspace_path: dev/dev01/canada-east
              module_path: modules/dev
              terraform_security_file_name: dev01-security-file
        - name: dev02
          ado_pipeline_environment: dev02
          locations:
            - name: canada-center
              workspace_path: dev/dev02/canada-center
              module_path: modules/dev
              terraform_security_file_name: dev02-security-file
            - name: canada-east
              workspace_path: dev/dev02/canada-east
              module_path: modules/dev
              terraform_security_file_name: dev02-security-file
        
    - workspace:
      - name: qa
      environments:
        - name: qa02
          ado_pipeline_environment: qa01
          locations:
            - name: canada-center
              workspace_path: qa/qa01/canada-center
              module_path: modules/qa
              terraform_security_file_name: qa01-security-file
            - name: canada-east
              workspace_path: qa/qa01/canada-east
              module_path: modules/qa
              terraform_security_file_name: qa01-security-file
        - name: qa02
          ado_pipeline_environment: qa02
          locations:
            - name: canada-center
              workspace_path: qa/qa02/canada-center
              module_path: modules/qa
              terraform_security_file_name: qa02-security-file
            - name: canada-east
              workspace_path: qa/qa02/canada-east
              module_path: modules/qa
              terraform_security_file_name: qa02-security-file

variables:
  tf_version: "1.0.5"

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - dev/**/**/*
    - modules/**/*
    - "*.tf"
    exclude:
    - "*.md"
    - "VERSION"

stages:
  - stage: setWorkspaceStage
    displayName: 'Workspace Check'
    pool:
      name: chancelenovo
    jobs:
      - job: setWorkspaceStage
        displayName: Workspace Check
        steps:
        - checkout: self
          fetchDepth: 0
        - ${{ each workspace in parameters.listWorkspaces }}:
          - ${{ each environment in workspace.environments }}:
            - ${{ each env_location in environment.locations }}:
              - bash: |
                  if [[ ${{ variables['Build.SourceBranch'] }} == *"master"* ]]; then
                    branch="HEAD^"
                  else
                    branch="origin/master"
                  fi

                  echo "branch_name: " ${{ variables['Build.SourceBranch'] }}
                  echo "Environment: " ${{ environment.name}}
                  echo "Location: " ${{ env_location.name }}
                  echo "Workspace Path: " ${{ env_location.workspace_path }}
                  echo "Module Path: " ${{ env_location.module_path }}

                  if git diff --quiet $branch -- ${{ env_location.workspace_path }} ${{ env_location.module_path }}; then
                    echo "${{ env_location.workspace_path }}: NOT changed"
                    echo "##vso[task.setvariable variable=isChange;isOutput=true]false"
                  else
                    echo "##[warning]WARNING: ${{ env_location.workspace_path }}: changed"
                    echo "##vso[task.setvariable variable=isChange;isOutput=true]true"
                  fi

            name: setWorkspaceTask_${{ environment.name }}_${{ env_location.name}}
            displayName: ${{ environment.name }}-${{ env_location.name}}
    
    
